version: '3.8'

services:
  app:
    build: .
    container_name: my-fastapi-app
    ports:
      - "80:8000"  # 외부 80포트로 들어오면 -> 내부 8000포트로 연결
    restart: always # 서버 재부팅되면 자동 실행
    env_file:
      - .env        # 환경변수 파일 연동